version: '3.8'

services:
  # خدمة PostgreSQL
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: property_db       # اسم قاعدة البيانات
      POSTGRES_USER: property_user     # يوزر
      POSTGRES_PASSWORD: property_pass # باسورد
    ports:
      - "5432:5432"  # ربط البورت على جهازك

  # خدمة Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379" # ربط البورت على جهازك

 postgres_data", "redis_data     